// packages/pureml_frontend/app/routes/models.tsx
import type { MetaFunction } from "@remix-run/node";
import { Outlet, useLoaderData } from "@remix-run/react";
import NavBar from "~/components/Navbar";
import { getSession } from "~/session";
import { fetchUserSettings } from "./api/auth.server";
import { fetchOrgDetails } from "./api/org.server";

export const meta: MetaFunction = () => ({
  charset: "utf-8",
  title: "Models | PureML",
  viewport: "width=device-width,initial-scale=1",
});

export async function loader({ request }: any) {
  const session = await getSession(request.headers.get("Cookie"));
  const accesstoken = session.get("accessToken");
  const profile = await fetchUserSettings(accesstoken);
  const orgId = session.get("orgId");
  const orgDetails = await fetchOrgDetails(orgId, session.get("accessToken"));
  return { profile, orgDetails };
}

export default function ModelsLayout() {
  const prof = useLoaderData();
  return (
    <div className="bg-slate-50 flex flex-col h-screen overflow-hidden">
      {prof ? (
        <NavBar
          intent="loggedIn"
          user={prof.profile[0].name.charAt(0).toUpperCase()}
          orgName={
            <a
              href={`/org/${prof.orgDetails[0].name}`}
              className="flex items-center justify-center"
            >
              {prof.orgDetails[0].name}
            </a>
          }
          orgAvatarName={prof.orgDetails[0].name.charAt(0)}
        />
      ) : (
        <NavBar
          intent="loggedOut"
          user=""
          orgName={
            <a href="/models" className="flex items-center justify-center pr-8">
              <img src="/PureMLLogoText.svg" alt="Logo" className="w-20" />
            </a>
          }
          orgAvatarName=""
        />
      )}
      <div className="flex justify-center w-full">
        <div className="bg-slate-50 flex flex-col h-screen overflow-hidden w-full 2xl:max-w-screen-2xl">
          <div className="flex justify-between px-12 pt-6 pb-4 font-medium text-slate-800">
            Models
          </div>
          <div className="h-[84%] overflow-auto pb-8">
            <Outlet />
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/pureml_sveltekit/src/routes/models/+page.svelte
<script>
  import Card from "$lib/components/Card.svelte";
  import Tag from "$lib/components/Tag.svelte";
  import { Box, Globe } from "lucide-svelte";
</script>

<div class="flex justify-center w-full">
  <div
    class="bg-slate-50 flex flex-col h-screen overflow-hidden w-full 2xl:max-w-screen-2xl"
  >
    <div
      class="flex justify-between px-12 pt-6 pb-4 font-medium text-slate-800"
    >
      Models
    </div>
    <div class="h-[84%] overflow-auto pb-8">
      <div
        class="px-12 pt-2 grid justify-center grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-6 4xl:grid-cols-10 gap-8 min-w-72"
      >
        <a href="/org/pureml/models/churn">
          <Card
            intent="badged"
            title="Model Name"
            description="My first model"
            count=""
            ><p slot="icon"><Box class="text-slate-400 w-4" /></p>
            <p slot="tag">
              <Tag
                ><p slot="icon"><Globe class="text-slate-400 w-4" /></p>
                <p slot="text">Public</p></Tag
              >
            </p></Card
          >
        </a>
      </div>
    </div>
  </div>
</div>
