// changelog/components/core/navbar/index.tsx
import { useState } from "react";
import { ArrowUpRight, Menu, X } from "lucide-react";
import clsx from "clsx";
import { useRouter } from "next/router";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";

function primaryLinkCss(currentPage: boolean) {
  return clsx(
    currentPage ? "text-slate-950 font-medium" : "text-slate-600",
    "w-full text-base letterSpaced hover:underline hover:underline-offset-2"
  );
}

export default function Navbar() {
  const [open, setOpen] = useState(true);
  const router = useRouter();
  const pathname = router.pathname;
  const navItems = [
    {
      id: "whypureml",
      name: "WHY PUREML",
      hyperlink: `https://pureml.com/whypureml`,
    },
    {
      id: "tools",
      name: "TOOLS",
      hyperlink: "",
      group: [
        { id: "mltools", name: "MLOPS", hyperlink: `https://pureml.com/mltools` },
        {
          id: "generativeAitools",
          name: "GENERATIVE AI",
          hyperlink: `https://pureml.com/generative-ai-tools`,
        },
      ],
    },
    {
      id: "resources",
      name: "RESOURCES",
      hyperlink: "",
      group: [
        { id: "docs", name: "DOCS", hyperlink: `https://pureml.mintlify.app` },
        {
          id: "changelog",
          name: "CHANGELOG",
          hyperlink: `https://changelog.pureml.com`,
        },
      ],
    },
  ];
  if (!open)
    return (
      <div className="flex justify-center">
        <div className="flex justify-center w-full backdrop-blur-sm bg-white/30">
          <div className="lg:h-fit w-full md:max-w-screen-xl px-0 md:px-8">
            <div className="sm:px-24">
              <div className="rounded-b-2xl border-b border-slate-200">
                <div className="flex px-4 py-4 md:px-12 justify-between">
                  <a href="https://pureml.com">
                    <img src="/PureMLLogoText.svg" alt="PureMLLogo" width="96" height="96" />
                  </a>
                  <X
                    className="sm:hidden text-slate-900 cursor-pointer w-8 h-8"
                    onClick={() => setOpen(!open)}
                  />
                </div>
                <div className="flex flex-col gap-y-4 p-4 font-medium text-brand-200">
                  <div className="flex items-center">
                    <a href="https://pureml.com/whypureml" className="w-max letterSpaced">
                      WHY PUREML
                    </a>
                  </div>
                  <div className="flex items-center">
                    <a href="https://pureml.com/mltools" className="w-max letterSpaced">
                      MLOPS TOOLS
                    </a>
                  </div>
                  <div className="flex items-center">
                    <a href="https://pureml.com/generative-ai-tools" className="w-max letterSpaced">
                      GENERATIVE AI TOOLS
                    </a>
                  </div>
                  <div className="flex items-center">
                    <a
                      href="https://changelog.pureml.com"
                      target="_blank"
                      rel="noreferrer"
                      className="w-max letterSpaced"
                    >
                      CHANGELOG
                    </a>
                  </div>
                  <div className="flex items-center">
                    <a
                      href="https://pureml.mintlify.app"
                      target="_blank"
                      rel="noreferrer"
                      className="w-max letterSpaced"
                    >
                      DOCS
                    </a>
                  </div>
                  <div className="flex items-center text-brand-200 letterSpaced">
                    <a href="https://pureml.com/auth/signin">SIGN IN</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  return (
    <div className="flex justify-center">
      <div className="flex justify-center w-full backdrop-blur-sm bg-white/30">
        <div className="lg:h-fit w-full md:max-w-screen-xl px-0 md:px-8">
          <div className="flex p-4 md:px-0 justify-between w-full">
            <a href="https://pureml.com">
              <img src="/PureMLLogoText.svg" alt="PureMLLogo" width="96" height="96" />
            </a>
            <div className="md:hidden flex">
              <div className="flex items-center pr-8">
                <a
                  className="sm:hidden github-button letterSpaced"
                  href="https://github.com/pureml-inc/pureml"
                  data-color-scheme="no-preference: dark_dimmed; light: light_high_contrast; dark: light;"
                  data-size="large"
                  data-show-count="true"
                  aria-label="Star pureml-inc/pureml on GitHub"
                >
                  STARS
                </a>
              </div>
              <div className="flex justify-center items-center">
                <Menu
                  className="sm:hidden text-slate-900 cursor-pointer w-8 h-8"
                  onClick={() => setOpen(!open)}
                />
              </div>
            </div>
            <div className="hidden sm:flex gap-x-4">
              {Object.keys(navItems).map((key: string) => (
                <div className="flex justify-center items-center" key={key}>
                  {navItems[key as any].group ? (
                    <DropdownMenu.Root>
                      <DropdownMenu.Trigger className="focus:outline-none z-50 flex justify-between items-center text-slate-600 text-base">
                        {navItems[key as any].name}
                      </DropdownMenu.Trigger>
                      <DropdownMenu.Content
                        sideOffset={7}
                        className="bg-white/75 justify-center items-center text-sm text-slate-600 rounded w-44 z-50 shadow"
                      >
                        {navItems[key as any].group.map((item: any) => (
                          <DropdownMenu.Item
                            className="flex px-3 py-2 text-base justify-left items-center rounded outline-none hover:bg-white/50 cursor-pointer"
                            key={item}
                          >
                            <a href={item.hyperlink}>{item.name}</a>
                          </DropdownMenu.Item>
                        ))}
                      </DropdownMenu.Content>
                    </DropdownMenu.Root>
                  ) : (
                    <a
                      href={navItems[key as any].hyperlink}
                      className={`${primaryLinkCss(pathname === navItems[key as any].hyperlink)}`}
                    >
                      {navItems[key as any].name}
                    </a>
                  )}
                </div>
              ))}
              <div className="flex justify-center items-center">
                <a
                  href="https://pureml.com/auth/signin"
                  className="flex justify-center items-center gap-y-4 text-brand-200 hover:underline hover:underline-offset-2 text-base letterSpaced"
                >
                  SIGN IN <ArrowUpRight className="text-brand-200 w-5" />
                </a>
              </div>
              <div className="flex justify-center items-center pt-1">
                <a
                  className="github-button flex justify-center items-center gap-y-4 text-brand-200 hover:underline hover:underline-offset-2 text-base letterSpaced"
                  href="https://github.com/pureml-inc/pureml"
                  data-color-scheme="no-preference: dark_dimmed; light: light_high_contrast; dark: light;"
                  data-size="large"
                  data-show-count="true"
                  aria-label="Star pureml-inc/pureml on GitHub"
                >
                  STAR
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/pureml_sveltekit/src/lib/components/Navbar.svelte
<script lang="ts">
  import { tv } from "tailwind-variants";
  import { Box, ChevronDown, Database, File, Menu, X } from "lucide-svelte";
  import Button from "$lib/components/Button.svelte";
  import clsx from "clsx";
  import { page } from "$app/stores";
  import Avatar from "$lib/components/Avatar.svelte";
  import Dropdown from "$lib/components/Dropdown.svelte";
  import logo from "$lib/logos/PureMLLogoText.svg";

  function linkCss(currentPage: boolean) {
    return clsx(
      currentPage ? " text-brand-200 font-medium " : " text-slate-500 ",
      " hover:text-brand-200 flex justify-center items-center px-5 cursor-pointer "
    );
  }

  const navbarStyles = tv({
    base: "navbar px-12 py-0 max-w-screen-2xl",
    variants: {
      intent: {
        loggedIn: "",
        loggedOut: "",
      },
      fullWidth: {
        true: "w-full",
      },
    },
    defaultVariants: {
      intent: "loggedOut",
      fullWidth: true,
    },
  });

  export let open = false;
  export let user: string;
  export let orgAvatarName: string;

  export let orgItems = [
    { link: "/switchOrg", title: "Switch Organization" },
    { link: "/joinOrg", title: "Join Organization" },
    { link: "/createOrg", title: "Create Organization" },
  ];

  export let profileItems = [
    { link: "/profile", title: "Profile" },
    { link: "/settings", title: "Settings" },
    // { link: "/contactus", title: "Contact Us" },
    { link: "/auth/signout", title: "Sign Out" },
  ];
</script>

{#if open}
  <ul class="bg-white rounded-b-2xl border-b border-slate-200">
    <div class="flex justify-between px-12 py-4 items-center">
      {#if $$restProps.intent === "loggedOut"}
        <li><img src={logo} alt="Logo" class="h-8" /></li>
      {:else}
        <li class="flex justify-center items-center pr-12">
          <Avatar>{orgAvatarName || "U"}</Avatar>
          <div class="px-2 font-medium text-slate-600">
            <slot name="orgName" />
          </div>
          <Dropdown intent="start">
            <p slot="trigger"><ChevronDown class="text-slate-400 w-4" /></p>
            <p slot="items">
              {#each orgItems as item}
                <li
                  class="flex px-3 py-2 text-sm justify-left items-center rounded outline-none hover:bg-slate-100 cursor-pointer"
                >
                  <a href={item.link} class="w-full">
                    {item.title}
                  </a>
                </li>
              {/each}
            </p>
          </Dropdown>
        </li>
      {/if}
      <button
        on:click={() => {
          open = !open;
        }}
      >
        <X class="sm:hidden text-slate-900 cursor-pointer w-8 h-8" /></button
      >
    </div>
    <div class="px-12 py-4">
      <li class="flex items-center">
        <a href="/models"> Models </a>
      </li>
      <li class="flex items-center">
        <a href="/datasets"> Datasets </a>
      </li>
      <li class="flex items-center">
        <a href="https://pureml.mintlify.app" class="w-max"> Docs </a>
      </li>
      {#if $$restProps.intent === "loggedOut"}
        <li class="flex">
          <div
            class="w-full flex justify-center items-center px-5 font-medium text-slate-500"
          >
            <a href="/auth/signin" class="w-max"> Sign in </a>
          </div>
          <div class="w-fit">
            <Button intent="primary">Sign up</Button>
          </div>
        </li>
      {:else}
        <li class="w-full flex items-center">
          <Dropdown intent="start">
            <p slot="trigger"><Avatar>{user || "U"}</Avatar></p>
            <p slot="items">
              {#each profileItems as item}
                <li
                  class="flex px-3 py-2 text-sm justify-left items-center rounded outline-none hover:bg-slate-100 cursor-pointer"
                >
                  <a href={item.link} class="w-full">
                    {item.title}
                  </a>
                </li>
              {/each}
            </p>
          </Dropdown>
        </li>
      {/if}
    </div>
    <li />
  </ul>
{:else}
  <div class="flex justify-center bg-slate-50 border-b border-slate-200">
    <div class={navbarStyles({ ...$$restProps })}>
      <ul class="flex w-full justify-between h-full">
        {#if $$restProps.intent === "loggedOut"}
          <li><img src={logo} alt="Logo" class="h-8" /></li>
        {:else}
          <li class="flex justify-center items-center pr-12 h-full">
            <div class="flex items-center h-full">
              <Avatar intent="primary">{orgAvatarName || "U"}</Avatar>
              <div class="px-2 text-slate-600">
                <slot name="orgName" />
              </div>
              <Dropdown intent="start">
                <p slot="trigger"><ChevronDown class="text-slate-400 w-4" /></p>
                <p slot="items">
                  {#each orgItems as item}
                    <li
                      class="flex px-3 py-2 text-sm justify-left items-center rounded outline-none hover:bg-slate-100 cursor-pointer"
                    >
                      <a href={item.link} class="w-full">
                        {item.title}
                      </a>
                    </li>
                  {/each}
                </p>
              </Dropdown>
            </div>
          </li>
        {/if}

        <button
          on:click={() => {
            open = !open;
          }}
          class="md:hidden"
        >
          <Menu
            class="sm:hidden text-slate-900 cursor-pointer w-8 h-8"
          /></button
        >
      </ul>

      <ul class="hidden md:flex md:justify-center items-center">
        <li>
          <a
            href="/models"
            class={`${linkCss($page.url.pathname === `/models`)}`}
          >
            <Box class="w-4 h-4" />
            <span class="pl-2">Models</span>
          </a>
        </li>
        <li>
          <a
            href="/datasets"
            class={`${linkCss($page.url.pathname === `/datasets`)}`}
          >
            <Database class="w-4 h-4" />
            <span class="pl-2">Datasets</span>
          </a>
        </li>
        <li>
          <a
            href="https://pureml.mintlify.app"
            class="flex justify-center items-center cursor-pointer px-5 hover:text-brand-200 text-slate-500"
          >
            <File class="w-4 h-4" />
            <span class="pl-2">Docs</span>
          </a>
        </li>
        {#if $$restProps.intent === "loggedOut"}
          <li class="flex">
            <div
              class="w-full flex justify-center items-center px-5 font-medium text-slate-500"
            >
              <a href="/auth/signin" class="w-max"> Sign in </a>
            </div>
            <div class="w-fit">
              <Button intent="primary">Sign up</Button>
            </div>
          </li>
        {:else}
          <!-- <Input
            on:click={handleMobileIconClick}
            intent="search"
          /> -->
          <li class="w-full flex justify-center items-center pl-5">
            <Dropdown intent="end">
              <Avatar intent="large">{user || "U"}</Avatar>
              <p slot="items">
                {#each profileItems as item}
                  <li
                    class="flex px-3 py-2 text-sm justify-left items-center rounded outline-none hover:bg-slate-100 cursor-pointer"
                  >
                    <a href={item.link} class="w-full">
                      {item.title}
                    </a>
                  </li>
                {/each}
              </p>
            </Dropdown>
          </li>
        {/if}
      </ul>
    </div>
  </div>
{/if}
